spring:
  application:
    name: manage-category-service
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
server:
  port: 9099
springdoc:
  swagger-ui:
    enabled: true
    path: /manage-category-service.html
  api-docs:
    enabled: true
    path: /manage-category-service-api
user: 
 data:
  duplicate: 
    message: The Data submitted may have already existed. Please check the data and submit once again
doctor:
  fee: 750
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manage-category-service
    #url: jdbc:mysql://medilab-user-service-mysql:3306/manage-category-service
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: stage
  h2:
    console:
      enabled: true
      path: /h2Console
